# Generated by Django 2.1 on 2020-07-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('days', models.ManyToManyField(blank=True, to='filterresult.Day')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ManyToManyField(blank=True, to='filterresult.Section'),
        ),
    ]
