# Generated by Django 2.1 on 2020-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterresult', '0002_auto_20200701_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classes',
        ),
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
