# Generated by Django 2.1 on 2020-07-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterresult', '0003_auto_20200702_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='num',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
