# Generated by Django 2.1 on 2020-07-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filterresult', '0004_section_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='filterresult.Section'),
        ),
    ]
