# Generated by Django 2.1 on 2020-07-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterresult', '0005_auto_20200713_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='days',
            field=models.CharField(max_length=5),
        ),
    ]
