# Generated by Django 2.1 on 2020-07-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterresult', '0006_auto_20200714_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ManyToManyField(blank=True, to='filterresult.Section'),
        ),
    ]
