# Generated by Django 2.1 on 2020-06-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filters',
            old_name='content',
            new_name='dpt',
        ),
    ]
