# Generated by Django 2.1 on 2020-06-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20200623_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filters',
            old_name='dpt',
            new_name='classname',
        ),
    ]
